include: 'rules/test.snakefile.py'
configfile: 'config/config.yml'
report: 'docs/snakemake_report/index.rst'

configfile: 'config.yml'

rule all:
    input:
        'docs/html/plot.html'
        , 'png/plot2.png'
        , 'docs/html/plot3.html'
        , 'testlog/check_utilR.txt'
        , 'docs/rst/readme.rst'
        , 'docs/index.rst'

rule load_dataset:
    output:
        'data/out/feather/data.feather'
    conda:
        'envs/snakemake_minimal_debian.yml'
    script:
        'src/py/load.py'

rule plot_rmd_direct:
    input:
        'data/out/feather/data.feather'
    output:
        report('docs/html/plot.html', category = 'plot')
    script:
        'src/Rmd/plot.Rmd'


rule plot_rmd_via_shell:
    input:
        'Rmd/plot2.Rmd'
        , 'feather/data.feather'
    output:
        report('docs/html/plot2.html', category = 'plot')
        , report('docs/png/plot2.png', category = 'plot')
    shell:
#     # snakemake removes all single quotation marks from a command therefore we use triple
#     # quotation for the outside string
        """R -e 'wd = getwd(); \
                  rmarkdown::render( "{input[0]}" \
                                  , output_file = normalizePath( paste0( wd,"/" ,"{output[0]}" ) ) \
                                  , params = list(in = "{input[1]}"  \
                                                  , out = "{output[1]}" ) \
                                  , knit_root_dir = getwd() \
                                  , envir = new.env() )' \
        """
        
rule plot_execute_nb_plot:
    conda:
        'envs/snakemake_minimal_debian.yml'
    input:
        'nb/vanilla/plot3.ipynb'
        , 'data/out/feather/data.feather'
    output:
        'nb/executed/plot3.ipynb'
    shell:
# using papermill offers better parametrisation than using snakemake
        """python -c 'import papermill as pm; \
            pm.execute_notebook(  "{input[0]}" \
                    , "{output[0]}" \
                    , parameters = dict( input = "{input[1:]}" )' \

        """
        
rule plot_nb_2_html:
    conda:
        'envs/snakemake_minimal_debian.yml'
    input:
        'nb/executed/plot3.ipynb'
    output:
        report('docs/html/plot3.html', category = 'plot')
    shell:
        'jupyter nbconvert --to html {input} {output}'



# Report -------------------------------------------------------------------------------------
# can't be put into an imported rule because of the report() tag for the README does not
# get resolved properly

rule report:
    input:
        'docs/rst/readme.rst',
        'Rmd/index.Rmd',
        'docs/index.rst'
        'docs/README.md'

rule readme_rst:
    input:
        'README.md'
    output:
        report('docs/rst/readme.rst', caption='docs/rst/readme.rst', category = 'README')
    shell:
        "pandoc {input} --from markdown --to rst -s -o {output}"

rule_copy_readme:
    input:
        "README.MD"
    output:
        "docs/README.MD"
    shell:
        "cp README.md docs/README.md"

rule index_md:
    output:
        'docs/index.md'
    script:
        'Rmd/index.Rmd'

rule index_rst:
    input:
        'docs/index.md'
    output:
        'docs/snakemake_report/index.rst'
    shell:
        "pandoc {input} --from markdown --to rst -s -o {output}"
