language: python

services:
  - docker

install:
  - pip install cookiecutter

script: 
  - cookiecutter https://github.com/erblast/cookie_ds --no-input
  - docker build -t {{cookiecutter.project_name}} --file {{cookiecutter.project_name}}/Dockerfile {{cookiecutter.project_name}}/.
  - docker run -v"$PWD/{{cookiecutter.project_name}}:/app/" {{cookiecutter.project_name}}
  - docker run -v"$PWD/{{cookiecutter.project_name}}:/app/" {{cookiecutter.project_name}} snakemake -F job
