language: python

services:
  - docker

install:
  - pip install cookiecutter

script: 
  - cookiecutter https://github.com/erblast/cookie_ds --no-input
  - docker build -t cookie_ds_demo --file cookie_ds_demo/Dockerfile cookie_ds_demo/.
  - docker run -v"$PWD/cookie_ds_demo:/app/" cookie_ds_demo
  - docker run -v"$PWD/cookie_ds_demo:/app/" cookie_ds_demo snakemake -F job