language: python

services:
  - docker

install:
  - pip install cookiecutter --no-input

script: 
  - cookiecutter https://github.com/erblast/cookie_ds
  - docker build -t cookie_ds_demo --file cookie_ds_demo/Dockerfile cookie_ds_demo/.
