---
title: "Index"
output: 
  md_document:
    variant: gfm
editor_options:
  chunk_output_type: console
params:
  rules_to_report:
    - exec
    - test
    - job
---
<!-- 
The content rendered from this file is used as a prefix for snakemake reports.
-->

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F, warning = F, message = F)
debug_file <-  paste0('debug/', 'index', '_rmd.Rdata')
save.image(debug_file)
```


```{r libraries, echo = FALSE}
suppressPackageStartupMessages( library('tidyverse') )
suppressPackageStartupMessages( library('knitr') )
suppressPackageStartupMessages( library('devtools') )
suppressPackageStartupMessages( devtools::load_all("src/{{cookiecutter.r_pkg_name}}") )
```

{{cookiecutter.description}}


### Documentation

- [{{cookiecutter.r_pkg_name}} documentation](https://erblast.github.io/{{cookiecutter.project_name}}//{{cookiecutter.r_pkg_name}}/index.html)

- [github repo](https://github.com/erblast/{{cookiecutter.project_name}}.git)

### Snakemake Reports


```{r echo = FALSE }
mdown_list <-  paste0("- [",
                      params$rules_to_report,
                      "](https://erblast.github.io/{{cookiecutter.project_name}}/snakemake_report/",
                      params$rules_to_report, 
                      '.html)' ) %>%
  paste( collapse = '\n')
```

`r mdown_list`

