version: '3.7'
services:
  build_image:
    build: .
    image: '{{cookiecutter.project_name}}'
    command: /bin/bash
    
  build_jup_image:
    build:
      context: .
      dockerfile: docker/jupyter.dockerfile
    image: '{{cookiecutter.project_name}}_jupyter'

  shell:
    image: '{{cookiecutter.project_name}}'
    working_dir: /app
    # make container wait
    command: tail -F anything
    volumes: 
      - '.:/app'
  rstudio:
    image: '{{cookiecutter.project_name}}'
    ports: 
      - '{{cookiecutter.rstudio_port}}:8787'
    volumes: 
      - '.:/home/rstudio/app'
    command: /init
    environment:
      PASSWORD: '{{cookiecutter.rstudio_password}}'
      USER: '{{cookiecutter.rstudio_user}}'
  
  jupyter:
    image: '{{cookiecutter.project_name}}_jupyter'
    ports:
      - '{{cookiecutter.jupyter_port}}:8888'
    volumes:
      - '.:/home/jovyan/work'
    environment:
      JUPYTER_TOKEN: '{{cookiecutter.jupyter_token}}'

  jekyll:
    image: jekyll/jekyll:pages
    ports:
      - '{{cookiecutter.jekyll_port}}:4000'
    volumes:
      - './docs:/srv/jekyll'
    command:
      jekyll serve
